kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: git-repo-secret
  namespace: argocd
  creationTimestamp: null
spec:
  template:
    metadata:
      name: git-repo-secret
      namespace: argocd
      creationTimestamp: null
  encryptedData:
    HTTPS_PASSWORD: AgA5IABH/v/qGUNQ6HUJPXqPTPGEt5VXvS0ex8tAMqL3goQV2N02LStC10WtwQL1blftXnkCQdIAIKizGo3PLZ93YzEPXHbciEQWjwLC7WN5qsy44fE/hy64ws4uIQ6tXY03mm4JROVZzxxVPZuhHW4WTwCHCAnruoQhIIbz1t5o6SbEfH6NSVCozEyQmoGIvMAzx8zC4h+HMgYHVZiAtd32vdfmyC2BOkKNmvdqw2j7tYEVVDIAJ1AFbE5eFZqhwso4FnCy2ZZJd/olYQsyUT/fo0vLjKdP73NYOzThv+nrYHi7tJ/4dIshChnTJg6FzbX//LYIHB1eYDzchNPuFVkX3uYFeFr9kRUpWgYmm3fhcl5vevpPDC2v4wNlIjPRKS1QnpIu+eJFHlvMolcInJ/7OMw57ePj+Is8askMGqucp7k8V3Xz7CkoXJPFE6SYOTflCgbxBF/7tm/uDAG6Lkcf2Ti87n4HuZvX7vOCf09UwVVGCLS021Rbrv2Els7VR/hvsCM2rtIBwWKtezwkB4iN/d720LjgQB4+dhSHVcwNnME67RXRXRD+fHuZRbEuX4KNS/b/mLsMN2+fen9kET+sT2Plg4QD288INsJ/X66rebMr+tiagI4gugzG9oFeJDsTnie+E6+unU/UmeE7MfDaKJ+tHHMbYhIGnS18mjUEPr+zAORb8Ek9oyQoZV78b9TEAMZ+oD2ZPjEcTUry
    HTTPS_USERNAME: AgAjsNZHDH70hA911LAa14azH2XQsfsm4mXDnweEsxhrl0j1tzkNMrfDOZz1psnAuGb5TRccl16VE35lKuT9zjD8aLRPvAdZfxgr/LKDTAWaITtikuEgcOikRC38H7Q1cqOWqhFoZ5CD2mqrhWA0161ttExzhE0k/fFrMOP7DsO1UedXhC/njAXAHPPc5XFVC17SQwFjprj7WNVOpUIA8vra/bZHfPtu3Qk7ZxZwYPefWczgPANna2TMUArI9tBxkaT+jZv/TFJgnRhbRYCW3dPCFo/L1/i6cXnNsIeX2MsA2G3ti6dtNrWB4IhTjTW/NoNCXpHLiW56FlqVMSsYomuoVRYMXXzHzbqJfn9FgHbqObI3kR19tLobQ75VInW70oXuPqdp0ege/P9wZyyM/zhleptj31taEZZaA40OjclOFDHIyvzUKqzMyVs79wBbg0OyTWKqRFVyV9q5LLWxMuPwFOy5ofin5KyvyS2cQ/uqo7a53wNnDE18SXwx0th1hDTX9ZQeCxZnTEf8o2tCdduDNZAxfC8FFjtuw0ddAYcnyTGaleyOwclgFv29YZE5USTlTnCq6q/h3Iy/Ww4SdN/nwPDooWYhBHK4uMuBx3P6HycQ/FohDwgusqEsZp5O/VT4ic//OkLAzkUVx+/lQXodCMcTBUNx/ebeI6JABMJfkiDCinfI21fMcC+7g0pVx5WHsM5qQIuZnyAWnprm9TQ4af7uM6GlLZs=
