kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
  encryptedData:
    admin-password: AgAT6T6SJEysBOgPBUu+1fWYS5AuWCD7VfRoV611ZTmOrRwQSWbY4HNa0Zhd/Rh0eqEpYL0KZzUqiW70use4Xiiemz9v9Rn7mT9vOfJQOcdQe7RHfE6SbbA+FZfaeCGt/eSI76rDvGgAAvyxjxCtMimj1vD0zuyJC6cSi517QqtFZW7ReYMTClIjxUrPghibbDrMTPcaJHz5o4TMjTVV7cGn4x35gra4B9kgGNXn7/YLlx9qjqQTfgfZ6uCBK3C3pXe9HEOO7e/d5F3h22k7MJtJuX9oEEL1aTVCy6J9/q7BJyBA5DHxt6ThfYRaD+13CLYXY4NPkxQfAyB1fmeW1z3ikXlilu7o9kQwfJy4+iMk/H1ozOOHone6C3vd58ehqc5yxpfJkHwBff71g71oLKZOHYRWsIOv4O1XawN70EZA/vpoRKYYVuQR6Wg5X5V3zkxvpAUKenuVz1O2RLiCP4wemsFGPzpwDTgvPt/OXHazKS3ALFn76ezmnW7G1n6l/n4P2sgiRWdpgbZ2+9Y7y8kIYaeqnz++To1qUx8QYCQRqM0qBGwGV9zVzJFqrn/UFyS4/vBMawZ5+EWaVaM/HkR1KLuxV03z5Jc/gb86VKePrRD87ZhttNE9Ntw50yoHVYENrryOTBpFqq+lEx35BNLdhOcnkSkFLnEvQ5i+VoMEB9yezCktl5ExHjNnVqZMljT9shOMqnI=
    admin-user: AgAy+udjjrTf9rbgRds4TWRe9DK1Oh+C1JjLf1aFEwcKiKYZpGMnuPcewG2iO4oo79Uqu70BUxG9Ec6TTqi4nKulK/qq3qPRn6zYrQlx2tr9GVIIiys4n1wbhlZKIrult+NnvEV4ZoH3Y4qv6yjSOOm22rDJVLUmmYqxO0bMGMatmjFlZC1wX5Eks/DvcEOB2vkynkUJ+dUlcVLQQ0QlIZogPgBZIRNWkqp9zploDC5VQo326EfJ7wwlxuMid/w9N0COpZLSy8Mfb7o4/7MIcXYbMmfP0Earn/az0uAS2dUwQuuOgd4Zaw+9DBtcnqrSQmE65NriVwAREMQcFWjNnsHL5/vAJejBJdUUFzXBKKvXJtqHDcVzwNLzAtUY89C8DTRWpmhelucvTUYkm81meytZWMFphrZKJyP7O1PmZBeILbv7Y0fW97Jmse4pUVwOKjwTozuPuc1rpXYXn9NYndqIuiBTr/ixOYL+8ksUTbQ9vz0ec40Sk0ZG5FVeT1oIEzSJyrcj/8qz5L4nTBAVfh8IdC57pFBp92c/QN7ByM4d6L21GycgpRph8VvLaiH9H+dlqGsSZ5DXT44mpZo1XK2d6AZXkYxJrG8/yoLMiuHA8WFYu1Mfr4OatK7qhaqfsU+gW51aVSb/qkJ0wqTVIsVz35uToVb/G7SKxUwMUW8vl6pDLdEH4f6NbmKe069k4NsLi7u3s7c=
